//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectsDTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostDTO", Namespace="http://schemas.datacontract.org/2004/07/ObjectsDTO")]
    public partial class PostDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ObjectsDTO.CommentDTO[] CommentsField;
        
        private int PostIdField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ObjectsDTO.CommentDTO[] Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId
        {
            get
            {
                return this.PostIdField;
            }
            set
            {
                this.PostIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentDTO", Namespace="http://schemas.datacontract.org/2004/07/ObjectsDTO", IsReference=true)]
    public partial class CommentDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CommentIdField;
        
        private string CommentTextField;
        
        private ObjectsDTO.PostDTO PostField;
        
        private int PostIdField;
        
        private int PostPostIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId
        {
            get
            {
                return this.CommentIdField;
            }
            set
            {
                this.CommentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentText
        {
            get
            {
                return this.CommentTextField;
            }
            set
            {
                this.CommentTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ObjectsDTO.PostDTO Post
        {
            get
            {
                return this.PostField;
            }
            set
            {
                this.PostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId
        {
            get
            {
                return this.PostIdField;
            }
            set
            {
                this.PostIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostPostId
        {
            get
            {
                return this.PostPostIdField;
            }
            set
            {
                this.PostPostIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPostComment")]
public interface IPostComment
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/Cleanup", ReplyAction="http://tempuri.org/IPost/CleanupResponse")]
    void Cleanup();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/Cleanup", ReplyAction="http://tempuri.org/IPost/CleanupResponse")]
    System.Threading.Tasks.Task CleanupAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetPostById", ReplyAction="http://tempuri.org/IPost/GetPostByIdResponse")]
    ObjectsDTO.PostDTO GetPostById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetPostById", ReplyAction="http://tempuri.org/IPost/GetPostByIdResponse")]
    System.Threading.Tasks.Task<ObjectsDTO.PostDTO> GetPostByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/SubmitPost", ReplyAction="http://tempuri.org/IPost/SubmitPostResponse")]
    bool SubmitPost(ObjectsDTO.PostDTO post);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/SubmitPost", ReplyAction="http://tempuri.org/IPost/SubmitPostResponse")]
    System.Threading.Tasks.Task<bool> SubmitPostAsync(ObjectsDTO.PostDTO post);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/UpdatePost", ReplyAction="http://tempuri.org/IPost/UpdatePostResponse")]
    ObjectsDTO.PostDTO UpdatePost(ObjectsDTO.PostDTO newPost);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/UpdatePost", ReplyAction="http://tempuri.org/IPost/UpdatePostResponse")]
    System.Threading.Tasks.Task<ObjectsDTO.PostDTO> UpdatePostAsync(ObjectsDTO.PostDTO newPost);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/DeletePost", ReplyAction="http://tempuri.org/IPost/DeletePostResponse")]
    int DeletePost(int postId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/DeletePost", ReplyAction="http://tempuri.org/IPost/DeletePostResponse")]
    System.Threading.Tasks.Task<int> DeletePostAsync(int postId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetAllPosts", ReplyAction="http://tempuri.org/IPost/GetAllPostsResponse")]
    ObjectsDTO.PostDTO[] GetAllPosts();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetAllPosts", ReplyAction="http://tempuri.org/IPost/GetAllPostsResponse")]
    System.Threading.Tasks.Task<ObjectsDTO.PostDTO[]> GetAllPostsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/GetCommentById", ReplyAction="http://tempuri.org/IComment/GetCommentByIdResponse")]
    ObjectsDTO.CommentDTO GetCommentById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/GetCommentById", ReplyAction="http://tempuri.org/IComment/GetCommentByIdResponse")]
    System.Threading.Tasks.Task<ObjectsDTO.CommentDTO> GetCommentByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/SubmitComment", ReplyAction="http://tempuri.org/IComment/SubmitCommentResponse")]
    bool SubmitComment(ObjectsDTO.CommentDTO comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/SubmitComment", ReplyAction="http://tempuri.org/IComment/SubmitCommentResponse")]
    System.Threading.Tasks.Task<bool> SubmitCommentAsync(ObjectsDTO.CommentDTO comment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/UpdateComment", ReplyAction="http://tempuri.org/IComment/UpdateCommentResponse")]
    ObjectsDTO.CommentDTO UpdateComment(ObjectsDTO.CommentDTO newComment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/UpdateComment", ReplyAction="http://tempuri.org/IComment/UpdateCommentResponse")]
    System.Threading.Tasks.Task<ObjectsDTO.CommentDTO> UpdateCommentAsync(ObjectsDTO.CommentDTO newComment);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadData/GetAllPostsAndRelatedComments", ReplyAction="http://tempuri.org/ILoadData/GetAllPostsAndRelatedCommentsResponse")]
    ObjectsDTO.PostDTO[] GetAllPostsAndRelatedComments();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadData/GetAllPostsAndRelatedComments", ReplyAction="http://tempuri.org/ILoadData/GetAllPostsAndRelatedCommentsResponse")]
    System.Threading.Tasks.Task<ObjectsDTO.PostDTO[]> GetAllPostsAndRelatedCommentsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPostCommentChannel : IPostComment, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PostCommentClient : System.ServiceModel.ClientBase<IPostComment>, IPostComment
{
    
    public PostCommentClient()
    {
    }
    
    public PostCommentClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PostCommentClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PostCommentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PostCommentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Cleanup()
    {
        base.Channel.Cleanup();
    }
    
    public System.Threading.Tasks.Task CleanupAsync()
    {
        return base.Channel.CleanupAsync();
    }
    
    public ObjectsDTO.PostDTO GetPostById(int id)
    {
        return base.Channel.GetPostById(id);
    }
    
    public System.Threading.Tasks.Task<ObjectsDTO.PostDTO> GetPostByIdAsync(int id)
    {
        return base.Channel.GetPostByIdAsync(id);
    }
    
    public bool SubmitPost(ObjectsDTO.PostDTO post)
    {
        return base.Channel.SubmitPost(post);
    }
    
    public System.Threading.Tasks.Task<bool> SubmitPostAsync(ObjectsDTO.PostDTO post)
    {
        return base.Channel.SubmitPostAsync(post);
    }
    
    public ObjectsDTO.PostDTO UpdatePost(ObjectsDTO.PostDTO newPost)
    {
        return base.Channel.UpdatePost(newPost);
    }
    
    public System.Threading.Tasks.Task<ObjectsDTO.PostDTO> UpdatePostAsync(ObjectsDTO.PostDTO newPost)
    {
        return base.Channel.UpdatePostAsync(newPost);
    }
    
    public int DeletePost(int postId)
    {
        return base.Channel.DeletePost(postId);
    }
    
    public System.Threading.Tasks.Task<int> DeletePostAsync(int postId)
    {
        return base.Channel.DeletePostAsync(postId);
    }
    
    public ObjectsDTO.PostDTO[] GetAllPosts()
    {
        return base.Channel.GetAllPosts();
    }
    
    public System.Threading.Tasks.Task<ObjectsDTO.PostDTO[]> GetAllPostsAsync()
    {
        return base.Channel.GetAllPostsAsync();
    }
    
    public ObjectsDTO.CommentDTO GetCommentById(int id)
    {
        return base.Channel.GetCommentById(id);
    }
    
    public System.Threading.Tasks.Task<ObjectsDTO.CommentDTO> GetCommentByIdAsync(int id)
    {
        return base.Channel.GetCommentByIdAsync(id);
    }
    
    public bool SubmitComment(ObjectsDTO.CommentDTO comment)
    {
        return base.Channel.SubmitComment(comment);
    }
    
    public System.Threading.Tasks.Task<bool> SubmitCommentAsync(ObjectsDTO.CommentDTO comment)
    {
        return base.Channel.SubmitCommentAsync(comment);
    }
    
    public ObjectsDTO.CommentDTO UpdateComment(ObjectsDTO.CommentDTO newComment)
    {
        return base.Channel.UpdateComment(newComment);
    }
    
    public System.Threading.Tasks.Task<ObjectsDTO.CommentDTO> UpdateCommentAsync(ObjectsDTO.CommentDTO newComment)
    {
        return base.Channel.UpdateCommentAsync(newComment);
    }
    
    public ObjectsDTO.PostDTO[] GetAllPostsAndRelatedComments()
    {
        return base.Channel.GetAllPostsAndRelatedComments();
    }
    
    public System.Threading.Tasks.Task<ObjectsDTO.PostDTO[]> GetAllPostsAndRelatedCommentsAsync()
    {
        return base.Channel.GetAllPostsAndRelatedCommentsAsync();
    }
}
